AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Parameters:
  VpcCidrBlock:
    Type: String
    Description: CIDR block for the VPC
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
  InternetAccess:
    Type: String
    Description: Whether the VPC should have access to internet
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  CreateInternetGateway: !Equals [!Ref InternetAccess, 'true']

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  InternetGateway:
    Condition: CreateInternetGateway
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-igw

  AttachGateway:
    Condition: CreateInternetGateway
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VpcId:
    Value: !Ref Vpc
  VpcCidrBlock:
    Value: !GetAtt Vpc.CidrBlock