AWSTemplateFormatVersion: 2010-09-09
Description: Network stack

Parameters:
  Project:
    Type: String
    Description: A name of a project
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Type: String
    Description: "Stage name. Typical values: dev, test, prod etc."
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,10}$
  Component:
    Type: String
    Description: Name of the system component
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,10}$
  Layer:
    Type: String
    Description: Name of the layer
    Default: network
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,10}$
  CfnNotificationTopicArn:
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !Ref CfnNotificationTopicArn
      Parameters:
        Project: !Ref Project
        Stage: !Ref Stage
        Component: !Ref Component
        Layer: !Ref Layer
        VpcName: vpc
        VpcCidrBlock: 10.0.0.0/16
        InternetAccess: 'true'
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Stage
          Value: !Ref Stage
        - Key: Component
          Value: !Ref Component
        - Key: Layer
          Value: !Ref Layer
      TemplateURL: ./network/vpc.yaml

  PublicSubnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !Ref CfnNotificationTopicArn
      Parameters:
        Project: !Ref Project
        Stage: !Ref Stage
        Component: !Ref Component
        Layer: !Ref Layer
        SubnetName: public-subnet
        VpcId: !GetAtt Vpc.Outputs.VpcIdParameterName
        CidrBlock: 10.10.0.0/24
        AvailabilityZoneIndex: 0
        IsPublic: 'true'
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Stage
          Value: !Ref Stage
        - Key: Component
          Value: !Ref Component
        - Key: Layer
          Value: !Ref Layer
      TemplateURL: ./network/subnet.yaml

  PrivateSubnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !Ref CfnNotificationTopicArn
      Parameters:
        Project: !Ref Project
        Stage: !Ref Stage
        Component: !Ref Component
        Layer: !Ref Layer
        SubnetName: private-subnet
        VpcId: !GetAtt Vpc.Outputs.VpcIdParameterName
        CidrBlock: 10.20.0.0/24
        AvailabilityZoneIndex: 0
        IsPublic: 'false'
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Stage
          Value: !Ref Stage
        - Key: Component
          Value: !Ref Component
        - Key: Layer
          Value: !Ref Layer
      TemplateURL: ./network/subnet.yaml
