AWSTemplateFormatVersion: 2010-09-09
Description: Shared resources

Parameters:
  Project:
    Type: String
    Description: A name of a project
    AllowedPattern: ^[A-Z][a-zA-Z0-9-]{3,15}$
  Stage:
    Type: String
    Description: "Stage name. Typical values: Dev, Test, Prod etc."
    AllowedPattern: ^[A-Z][a-zA-Z0-9-]{3,10}$
  Component:
    Type: String
    Description: Name of the component (layer)
    AllowedPattern: ^[A-Z][a-zA-Z0-9-]{3,10}$

Resources:
  SharedResources:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      NotificationARNs:
        - String
      Parameters:
        Map
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Stage
          Value: !Ref Stage
        - Key: Component
          Value: !Ref Component
      TemplateURL: ./shared/resources.yaml

  Parameters:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      NotificationARNs:
        - String
      Parameters:
        Project: !Ref Project
        Stage: !Ref Stage
        Component: !Ref Component
        TemplatesBucketName: !GetAtt SharedResources.Outputs.TemplatesBucketName
        CfnNotificationsTopicArn: !GetAtt SharedResources.Outputs.CfnNotificationsTopicArn
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Stage
          Value: !Ref Stage
        - Key: Component
          Value: !Ref Component
      TemplateURL: ./shared/parameters.yaml