AWSTemplateFormatVersion: 2010-09-09
Description: Shared resources for the whole environment

Parameters:
  Project:
    Type: String
    Description: A name of a project
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  Stage:
    Type: String
    Description: "Stage name. Typical values: dev, test, prod etc."
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,10}$
  Component:
    Type: String
    Description: Name of the system component
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,10}$

Resources:
  TemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Component}-${Stage}-TemplatesBucket

  CfnNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${Project}-${Component}-${Stage}-CfnNotificationsTopic
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Component}-${Stage}-CfnNotificationsTopic

Outputs:
  TemplatesBucketName:
    Value: !Ref TemplatesBucket
  CfnNotificationsTopicArn:
    Value: !Ref CfnNotificationsTopic